"""Event taxonomy definitions and descriptive classification helpers."""

from __future__ import annotations

from enum import Enum


class EventTaxonomy(str, Enum):
    UPWARD_EXPANSION = "UPWARD_EXPANSION"
    DOWNWARD_EXPANSION = "DOWNWARD_EXPANSION"
    VOLATILITY_EXPANSION = "VOLATILITY_EXPANSION"
    VOLUME_EXPANSION = "VOLUME_EXPANSION"
    BREAKOUT_CANDIDATE = "BREAKOUT_CANDIDATE"
    BREAKDOWN_CANDIDATE = "BREAKDOWN_CANDIDATE"
    COMPRESSION = "COMPRESSION"
    REVERSAL_CANDIDATE = "REVERSAL_CANDIDATE"
    ANOMALY_CANDIDATE = "ANOMALY_CANDIDATE"


class OutcomeTaxonomy(str, Enum):
    EVENT_CONTINUATION = "EVENT_CONTINUATION"
    FAILED_EXPANSION = "FAILED_EXPANSION"
    FALSE_BREAKOUT_CANDIDATE = "FALSE_BREAKOUT_CANDIDATE"
    FALSE_BREAKDOWN_CANDIDATE = "FALSE_BREAKDOWN_CANDIDATE"
    COMPRESSION_REGIME = "COMPRESSION_REGIME"
    EVENT_OBSERVATION = "EVENT_OBSERVATION"
